# Generated by Django 5.2.17 on 2026-08-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility_name", models.CharField(max_length=100, verbose_name="시설명")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="facilities/",
                        verbose_name="이미지",
                    ),
                ),
                ("addr", models.CharField(max_length=200, verbose_name="주소")),
                ("latit", models.FloatField(verbose_name="위도")),
                ("longit", models.FloatField(verbose_name="경도")),
                (
                    "station",
                    models.CharField(blank=True, max_length=100, verbose_name="가까운역"),
                ),
                (
                    "bus",
                    models.CharField(blank=True, max_length=100, verbose_name="가까운정류장"),
                ),
                (
                    "station_wt",
                    models.IntegerField(blank=True, null=True, verbose_name="역 도보시간"),
                ),
                (
                    "bus_wt",
                    models.IntegerField(blank=True, null=True, verbose_name="정류장 도보시간"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(max_length=200, verbose_name="프로그램명"),
                ),
                (
                    "program_day",
                    models.CharField(blank=True, max_length=50, verbose_name="수업 요일"),
                ),
                (
                    "program_cap",
                    models.IntegerField(blank=True, null=True, verbose_name="수용인원"),
                ),
                (
                    "program_time",
                    models.CharField(blank=True, max_length=50, verbose_name="수업 시간"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="별점")),
                ("content", models.TextField(blank=True, verbose_name="리뷰내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport_name",
                    models.CharField(max_length=50, unique=True, verbose_name="종목명"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subfacility_name",
                    models.CharField(max_length=100, verbose_name="세부시설명"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacilityDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "op_hour",
                    models.CharField(blank=True, max_length=100, verbose_name="운영시간"),
                ),
                (
                    "in_out",
                    models.CharField(blank=True, max_length=20, verbose_name="실내외 구분"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="전화번호"),
                ),
                ("website", models.URLField(blank=True, verbose_name="URL")),
                (
                    "fee",
                    models.CharField(blank=True, max_length=100, verbose_name="이용료"),
                ),
                (
                    "team_person",
                    models.CharField(blank=True, max_length=20, verbose_name="단체/개인"),
                ),
                ("shower", models.BooleanField(default=False, verbose_name="샤워실 유무")),
                ("parking", models.BooleanField(default=False, verbose_name="주차장 유무")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="facilities.facility",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacilitySport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_sports",
                        to="facilities.facility",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="facilities.facility",
                    ),
                ),
            ],
        ),
    ]
