# Generated by Django 5.2.17 on 2026-08-09 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="facilities.facility",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="facilities.facility",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facilitysport",
            name="sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_sports",
                to="facilities.sport",
            ),
        ),
        migrations.AddField(
            model_name="subfacility",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_facilities",
                to="facilities.facility",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="subfacility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="facilities.subfacility",
            ),
        ),
        migrations.AddField(
            model_name="facilitydetail",
            name="subfacility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="facilities.subfacility",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "facility")},
        ),
        migrations.AlterUniqueTogether(
            name="facilitysport",
            unique_together={("facility", "sport")},
        ),
    ]
