# Generated by Django 6.1 on 2026-08-30 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitydetail',
            name='subfacility',
        ),
        migrations.RemoveField(
            model_name='facilitydetail',
            name='team_person',
        ),
        migrations.CreateModel(
            name='SubFacilityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
                ('contents', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfacility_details', to='facilities.facility')),
                ('subfacility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='facilities.subfacility')),
            ],
        ),
    ]
