# Generated by Django 6.1 on 2026-09-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0003_remove_facilitydetail_subfacility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subfacilitydetail",
            name="agree_count",
            field=models.IntegerField(default=0, verbose_name="동의수"),
        ),
        migrations.AddField(
            model_name="subfacilitydetail",
            name="disagree_count",
            field=models.IntegerField(default=0, verbose_name="비동의수"),
        ),
    ]
