# Generated by Django 6.1 on 2026-09-07 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_subfacilitydetail_agree_count_and_more'),]

    operations = [
        migrations.AddField(
            model_name='program',
            name='subfacility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='facilities.subfacility'),
        ),
    ]
