# Generated by Django 6.1 on 2026-09-14 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0005_subfacilitydetail_agree_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="reviews/", verbose_name="사진"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="facilities.program",
            ),
        ),
    ]
