# Generated by Django 6.1 on 2026-09-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0006_review_image_review_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_oneday",
            field=models.BooleanField(default=False, verbose_name="원데이 리뷰 여부"),
        ),
    ]
