# Generated by Django 6.1 on 2026-09-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0007_review_is_oneday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitydetail",
            name="parking",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="주차장 유무"
            ),
        ),
        migrations.AlterField(
            model_name="facilitydetail",
            name="shower",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="샤워실 유무"
            ),
        ),
    ]
