# Generated by Django 6.1 on 2026-09-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0009_facilitydetail_amenities_unknown"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitydetail",
            name="closed_day",
            field=models.CharField(blank=True, max_length=50, verbose_name="휴관일"),
        ),
        migrations.AddField(
            model_name="facilitydetail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일시"),
        ),
        migrations.AddField(
            model_name="facilitydetail",
            name="weekend_op_hour",
            field=models.CharField(blank=True, max_length=100, verbose_name="주말 운영시간"),
        ),
        migrations.AlterField(
            model_name="facilitydetail",
            name="op_hour",
            field=models.CharField(blank=True, max_length=100, verbose_name="평일 운영시간"),
        ),
    ]
