# Generated by Django 6.1 on 2026-09-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "facilities",
            "0010_facilitydetail_closed_day_facilitydetail_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitydetail",
            name="website",
            field=models.CharField(blank=True, max_length=200, verbose_name="URL"),
        ),
    ]
