"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url


# =========================================================
# 기본 경로
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# 보안 / 배포 환경 설정
# =========================================================

# 로컬에서는 아래 기본값 사용
# 배포 서버에서는 Environment Variable의 SECRET_KEY 사용
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-development-key"
)

# 로컬 기본값은 True
# 배포 서버에서는 DEBUG=False 환경변수를 등록
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"


# 로컬 + 배포 서버 모두 대응
# 배포 서버에서는 ALLOWED_HOSTS 환경변수로
# 예: gong-teo-api.onrender.com
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ALLOWED_HOSTS",
        "localhost,127.0.0.1"
    ).split(",")
    if host.strip()
]


# =========================================================
# Application definition
# =========================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 우리 앱
    'users',
    'facilities',
    'oneday',

    # 외부 패키지
    'rest_framework',
    'corsheaders',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # CORS
    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# =========================================================
# Database
# =========================================================
#
# 로컬:
# DATABASE_URL 환경변수가 없으므로 기존 db.sqlite3 사용
#
# 배포:
# Render 등에 DATABASE_URL을 등록하면 PostgreSQL 사용
#

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# =========================================================
# Password validation
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================
# Internationalization
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# =========================================================
# Static files
# =========================================================

STATIC_URL = '/static/'

# collectstatic 실행 시 파일이 모이는 위치
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise를 이용한 static 파일 처리
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# CLOUDINARY_URL 환경변수가 있으면 업로드 이미지를 Cloudinary에 저장한다.
# (Render 무료 플랜은 디스크가 영구 저장소가 아니고, DEBUG=False에서는
#  /media/ 를 서빙하지 않아서 배포 환경에서는 반드시 필요하다.)
# 환경변수가 없는 로컬 개발 환경에서는 기존처럼 MEDIA_ROOT 폴더를 사용한다.
if os.environ.get("CLOUDINARY_URL"):
    STORAGES["default"] = {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    }


# =========================================================
# Media files
# =========================================================
#
# facility image, proof_image 등 업로드하는 이미지
#
# 배포 환경에서는 위 STORAGES 설정에 따라 Cloudinary에 저장되고,
# 이 MEDIA_URL/MEDIA_ROOT는 로컬 개발 환경에서만 실제로 쓰인다.
#

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# =========================================================
# Email
# =========================================================
#
# 비밀번호 재설정 인증번호 발송에 사용.
#
# 로컬에서 EMAIL_HOST_USER / EMAIL_HOST_PASSWORD 환경변수가 없으면
# 콘솔(터미널)에 이메일 내용을 출력하는 것으로 대체한다.
# 실제 발송을 테스트하려면 아래 환경변수를 .env 등에 설정할 것:
#   EMAIL_HOST_USER=발신용 지메일 주소
#   EMAIL_HOST_PASSWORD=지메일 앱 비밀번호 (일반 로그인 비밀번호 아님)
#
# Gmail 앱 비밀번호는 구글 계정 > 보안 > 2단계 인증 활성화 후
# "앱 비밀번호"에서 발급받아야 함.
#

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = True
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "noreply@gong-teo.local"


# =========================================================
# Custom User Model
# =========================================================

AUTH_USER_MODEL = 'users.User'


# =========================================================
# CORS
# =========================================================
#
# 로컬 React 주소는 기본으로 허용.
#
# 배포 후:
# CORS_ALLOWED_ORIGINS 환경변수에
# 실제 React 배포 주소를 넣으면 됨.
#
# 예:
# https://gong-teo.vercel.app
#

DEFAULT_CORS_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

ENV_CORS_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "CORS_ALLOWED_ORIGINS",
        ""
    ).split(",")
    if origin.strip()
]

CORS_ALLOWED_ORIGINS = (
    DEFAULT_CORS_ORIGINS
    + ENV_CORS_ORIGINS
)


# =========================================================
# Django REST Framework
# =========================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}


# =========================================================
# Simple JWT
# =========================================================
#
# 기본 ACCESS_TOKEN_LIFETIME(5분)이 너무 짧아서
# 현재 프로젝트에서는 1시간으로 사용
#

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
}


# =========================================================
# Logging
# =========================================================
#
# DEBUG=False (배포 환경)에서는 Django 기본 설정상 500 에러가
# mail_admins 핸들러로만 전달되는데, ADMINS가 비어 있어서
# 실제로는 아무 데도 기록되지 않고 사라진다.
#
# Render는 stdout을 로그로 수집하므로, django.request 로거를
# 콘솔 핸들러에 연결해서 500 에러 발생 시 Traceback이
# 배포 로그에 그대로 보이도록 한다.
#

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}