# Generated by Django 5.2.17 on 2026-08-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnedayApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apply_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신청 일시"),
                ),
                (
                    "apply_result",
                    models.CharField(
                        choices=[
                            ("waiting", "대기"),
                            ("assigned", "배정"),
                            ("rejected", "미배정"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="배정 결과",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnedayPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_date", models.DateField(verbose_name="양도 날짜")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "모집중"), ("closed", "마감")],
                        default="open",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="게시 일시"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="수강 시작일")),
                ("end_date", models.DateField(verbose_name="수강 종료일")),
                (
                    "program_day",
                    models.CharField(blank=True, max_length=50, verbose_name="수강 요일"),
                ),
                (
                    "program_time",
                    models.CharField(blank=True, max_length=50, verbose_name="수업 시간"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "승인대기"),
                            ("approved", "승인"),
                            ("rejected", "반려"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="승인 상태",
                    ),
                ),
                (
                    "reject_reason",
                    models.CharField(blank=True, max_length=200, verbose_name="반려 사유"),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="facilities.program",
                    ),
                ),
            ],
        ),
    ]
