# Generated by Django 6.1 on 2026-09-07 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_remove_facilitydetail_subfacility_and_more'),
        ('oneday', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprogram',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='program_proofs/', verbose_name='수강증'),
        ),
        migrations.AddField(
            model_name='myprogram',
            name='subfacility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_programs', to='facilities.subfacility'),
        ),
    ]
