# Generated by Django 6.1 on 2026-09-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oneday", "0003_myprogram_proof_image_myprogram_subfacility"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="onedaypost",
            constraint=models.UniqueConstraint(
                fields=("enroll", "transfer_date"), name="unique_enroll_transfer_date"
            ),
        ),
    ]
